/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.pessoas;
import java.util.ArrayList;

/**
 *
 * @author arocha
 */
public class telaLista extends javax.swing.JFrame {

    
    private ArrayList<pessoas> ListaPessoas = new ArrayList();
    
    /**
     * Creates new form telaLista
     */
    public telaLista() {
        initComponents();
    }
    
    public void ListaDePessoas(){
        textListaPessoas.setText("");
        for (int i = 0; i <getListaPessoas().size(); i++) {
            textListaPessoas.setText(textListaPessoas.getText() + 
            "ID" + i + ", " + getListaPessoas().get (i).mostraDados() + "\n");
        }
    }
    
    public void cadastroDePessoa (pessoas pessoa){
        getListaPessoas().add(pessoa);
    }
    
    public void atualizarPessoas(int id, String novoNome, int novaIdade, String novoCpf){
                getListaPessoas().get(id).setNome(novoNome);
                    getListaPessoas().get(id).setIdade(novaIdade);
                        getListaPessoas().get(id).setCpf(novoCpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCadastraLista = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textListaPessoas = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        textIDdelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela Listagem");

        botaoCadastraLista.setText("Cadastrar");
        botaoCadastraLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraListaActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoDeletar.setText("Deletar");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        textListaPessoas.setColumns(20);
        textListaPessoas.setRows(5);
        jScrollPane1.setViewportView(textListaPessoas);

        jLabel2.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCadastraLista)
                                .addGap(33, 33, 33)
                                .addComponent(botaoAlterar)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textIDdelete))
                                    .addComponent(botaoDeletar))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textIDdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastraLista)
                    .addComponent(botaoAlterar)
                    .addComponent(botaoDeletar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastraListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraListaActionPerformed
        // TODO add your handling code here:
        telaCadastro telaCad = new telaCadastro(this);
        telaCad.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoCadastraListaActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        // TODO add your handling code here:
        
        TelaAtualizar telaAtu = new TelaAtualizar(this);
        telaAtu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        // TODO add your handling code here:
        ListaPessoas.remove(Integer.parseInt(textIDdelete.getText()));
        
        ListaDePessoas();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCadastraLista;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textIDdelete;
    private javax.swing.JTextArea textListaPessoas;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ListaPessoas
     */
    public ArrayList<pessoas> getListaPessoas() {
        return ListaPessoas;
    }

    /**
     * @param ListaPessoas the ListaPessoas to set
     */
    public void setListaPessoas(ArrayList<pessoas> ListaPessoas) {
        this.ListaPessoas = ListaPessoas;
    }
}
